name: 'Enrich Pull Request'
description: "Enrich's the pull request with information from your project management system."
inputs:
    repository:
        description: 'The repository name'
        required: true
        type: string
    pullRequestNumber:
        description: 'The pull request number'
        required: true
        type: string
    branch:
        description: 'The branch name'
        required: true
        type: string
    token:
        description: 'GitHub token'
        required: true
    customFormatting:
        description: "User defined custom formatting rules for specific words."
        required: false
        default: ""
    strategy:
        description: 'Which formatting strategy should be used'
        required: false
        default: 'branch-name'
        type: string
runs:
    using: 'docker'
    image: 'docker://ghcr.io/encoredigitalgroup/gh-action-create-github-release:latest'
    env:
        GH_TOKEN: ${{ inputs.token }}
        GH_REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pullRequestNumber }}
        BRANCH_NAME: ${{ inputs.branch }}
        ENABLE_EXPERIMENTS: ${{ inputs.enableExperiments }}
        CI_FMT_WORDS: ${{ inputs.customFormatting }}
        CI_FMT_STRATEGY: ${{ inputs.strategy }}