name: 'JSON Diff Alert'
description: 'Compares JSON keys between source and destination files and comments on PR with differences'
inputs:
    repository:
        description: 'The repository name (org/repo)'
        required: true
        type: string
    pullRequestNumber:
        description: 'The pull request number'
        required: true
        type: string
    token:
        description: 'GitHub token'
        required: true
    sourceFile:
        description: 'Path to the source JSON file to compare from'
        required: true
        type: string
    destinationFiles:
        description: 'Comma-separated list of destination JSON files to compare against'
        required: true
        type: string
    rootDirectory:
        description: 'Root directory for resolving relative file paths. Defaults to $GITHUB_WORKSPACE if not provided.'
        required: false
        type: string
        default: ${{ github.workspace }}
runs:
    using: 'docker'
    image: 'docker://ghcr.io/encoredigitalgroup/gh-action-json-diff-alert:latest'
    env:
        GH_TOKEN: ${{ inputs.token }}
        GH_REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pullRequestNumber }}
        SOURCE_FILE: ${{ inputs.sourceFile }}
        DESTINATION_FILES: ${{ inputs.destinationFiles }}
        ROOT_DIRECTORY: ${{ inputs.rootDirectory }}