name: Rector
inputs:
    branch:
        type: string
        required: false
        default: main
    repository:
        type: string
        required: true
    phpVersion:
        type: string
        required: false
        default: "8.3"



runs:
    using: 'composite'
    steps:
        -   name: Deprecation Warning
            shell: bash
            run: echo "This action is deprecated. Use the codeStyle action instead."

        -   uses: shivammathur/setup-php@v2
            with:
                php-version: "${{ inputs.phpVersion }}"

        -   name: Checkout Action
            uses: actions/checkout@v4

        -   name: Checkout Repository
            uses: actions/checkout@v4
            with:
                repository: "${{ inputs.repository }}"
                ref: "${{ inputs.branch }}"

        -   name: Set execute permissions
            shell: bash
            run: chmod +x ${{github.action_path}}/entrypoint.sh

        -   name: Run Rector
            shell: bash
            env:
                GH_ACTION_PATH: ${{ github.action_path }}
            run: ${{github.action_path}}/entrypoint.sh