name: 'Format Pull Request Title'
description: 'Formats the pull request title based on the branch name'
inputs:
    repository:
        description: 'The repository name'
        required: true
        type: string
    pullRequestNumber:
        description: 'The pull request number'
        required: true
        type: string
    branch:
        description: 'The branch name'
        required: true
        type: string
    token:
        description: 'GitHub token'
        required: true
    useGo:
        description: 'Use the Go version of the action. Default is false'
        required: false
        default: false
        type: boolean
runs:
    using: 'composite'
    steps:
        -   name: Setup Go
            if: ${{ inputs.useGo }}
            uses: actions/setup-go@v5
            with:
                go-version: "${{ github.action_path }}/go.mod"
                cache-dependency-path: "${{ github.action_path }}/go.sum"


        -   name: "Format Pull Request Title (Go) [WARNING: This is an experimental feature]"
            if: ${{ inputs.useGo }}
            shell: bash
            run: go run ${{github.action_path}}/main.go
            env:
                GH_TOKEN: ${{ inputs.token }}
                GH_REPOSITORY: ${{ inputs.repository }}
                PR_NUMBER: ${{ inputs.pullRequestNumber }}
                BRANCH_NAME: ${{ inputs.branch }}

        -   name: Set execute permissions
            if: ${{ !inputs.useGo }}
            shell: bash
            run: chmod +x ${{github.action_path}}/entrypoint.sh

        -   name: Format Pull Request Title
            if: ${{ !inputs.useGo }}
            shell: bash
            run: ${{github.action_path}}/entrypoint.sh
            env:
                GH_TOKEN: ${{ inputs.token }}
                GH_REPOSITORY: ${{ inputs.repository }}
                PR_NUMBER: ${{ inputs.pullRequestNumber }}
                BRANCH_NAME: ${{ inputs.branch }}
