name: 'Format Pull Request Title'
description: 'Formats the pull request title based on the branch name'
inputs:
    repository:
        description: 'The repository name'
        required: true
        type: string
    pullRequestNumber:
        description: 'The pull request number'
        required: true
        type: string
    branch:
        description: 'The branch name'
        required: true
        type: string
    token:
        description: 'GitHub token'
        required: true
    customFormatting:
        description: "User defined custom formatting rules for specific words."
        required: false
        default: ""
    useGo:
        description: 'Use the Go version of the action. Default is false [NOTICE: This option will be removed in the next major version.]'
        required: false
        default: false
        type: boolean

runs:
    using: 'docker'
    image: 'docker://ghcr.io/encoredigitalgroup/gh-action-format-pull-request-title:latest'
    env:
        GH_TOKEN: ${{ inputs.token }}
        GH_REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pullRequestNumber }}
        BRANCH_NAME: ${{ inputs.branch }}
        CI_FMT_WORDS: ${{ inputs.customFormatting }}