name: "0_Local: Create Release"

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '!v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
            - '!v[0-9]'
    workflow_dispatch:

permissions:
    pull-requests: write
    contents: write

jobs:
    CreateRelease:
        name: Create Release
        uses: ./.github/workflows/github_createRelease.yml
        with:
            generateReleaseNotes: true
            isDraft: false
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}

    PrepareTags:
        name: PrepareTags
        runs-on: ubuntu-latest
        steps:
            -   name: ReplaceMajorTag
                id: replaceMajorTag
                run: |
                    git fetch --tags
                    git tag -d v2
                    git push origin --delete v2
                    git tag v1 ${{github.ref}}
                    git push origin v2
