name: "0_Local: Create Release"

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '!v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
            - '!v[0-9]'
    workflow_dispatch:

permissions:
    pull-requests: write
    contents: write
    packages: write

jobs:
    BuildActionImages:
        name: Build Action Images
        strategy:
            matrix:
                include:
                    -   actionPath: 'actions/github/createRelease'
                        imageName: 'gh-action-create-github-release'
                    -   actionPath: 'actions/github/jsonDiffAlert'
                        imageName: 'gh-action-json-diff-alert'
        uses: ./.github/workflows/_github_createAndReleaseActionDockerImage.yml
        with:
            actionPath: ${{ matrix.actionPath }}
            imageName: ${{ matrix.imageName }}
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}

    CreateRelease:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            -   name: Create Release
                uses: ./actions/github/createRelease
                with:
                    generateReleaseNotes: true
                    isDraft: false
                    repository: ${{ github.repository }}
                    tagName: ${{ github.head_ref }}
                    token: ${{ secrets.GITHUB_TOKEN }}

    PrepareTags:
        name: PrepareTags
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: ReplaceMajorTag
                id: replaceMajorTag
                run: |
                    git fetch --tags
                    major_version=$(echo "${GITHUB_REF#refs/tags/}" | grep -oP '^v\K[0-9]+')
                    git tag -d v$major_version
                    git push origin --delete v$major_version
                    git tag v$major_version ${{github.ref}}
                    git push origin v$major_version