name: Static Analysis

on:
    workflow_call:
        inputs:
            branch:
                type: string
                required: false
                default: "main"
            goVersion:
                type: string
                required: false
                default: "1.21"

jobs:
    StaticAnalysis:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.branch }}

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ inputs.goVersion }}

            -   name: Run golangci-lint
                uses: golangci/golangci-lint-action@v6