name: Static Analysis

on:
    workflow_call:
        inputs:
            branch:
                type: string
                required: false
                default: "main"
            goVersion:
                type: string
                required: false
                default: "1.24"
            timeout:
                type: string
                required: false
                default: '1m'
            onlyNew:
                type: boolean
                required: false
                default: false

jobs:
    StaticAnalysis:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.branch }}

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ inputs.goVersion }}

            -   name: Run golangci-lint
                uses: golangci/golangci-lint-action@v6
                with:
                    only-new-issues: ${{ inputs.onlyNew }}
                    args: --timeout=${{ inputs.timeout }}
