name: PHPUnit

on:
    workflow_call:
        inputs:
            phpVersion:
                type: string
                description: 'PHP Version'
                required: false
                default: '8.3'

jobs:
    RunPHPUnit:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.phpVersion }}
                    tools: composer:v2
                    coverage: xdebug

            -   name: Restore Composer Cache
                uses: actions/cache/restore@v4
                id: restoreComposerCache
                with:
                    path: ~/.composer/cache
                    key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

            -   name: Install Dependencies
                run: composer install --no-interaction --prefer-dist --optimize-autoloader

            -   name: Save Composer Cache
                uses: actions/cache/save@v4
                id: saveComposerCache
                with:
                    path: ~/.composer/cache
                    key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

            -   name: Run PHPUnit Test
                run: ./vendor/bin/phpunit